# name: Deployment

# on:
#   push:
#     branches:
#       - {branch-name}

# jobs:
#   deployment:
#     runs-on: ubuntu-latest
#     steps:
#       - name: get latest code
#         uses: actions/checkout@v2

#       - name: use node.js 16
#         uses: actions/setup-node@v2
#         with:
#           node-version: "16"

#       - name: install dependencies
#         run: npm install

#       - name: build project
#         run: gulp deploy --production

#       - name: sync files
#         uses: SamKirkland/FTP-Deploy-Action@4.3.0
#         with:
#           server: { ftp hostname }
#           username: { ftp username }
#           password: ${{ secret ftp password }}
#           local-dir: { local directory }
#           server-dir: { remote directory }
